### ISSUE TITLE
Consolidate find_bulge_loop,  shortest_bg_loop and find_multiloop_loops somehow.

### ISSUE THREAD

**Issue by Bernhard10** [ViennaRNA/forgi#10]
A bulge graph has the member functions
-  find_bulge_loop
-  shortest_bg_loop
- find_multiloop_loops, which depends on shorthest_bg_loop

There are no tests for find_bulge_loop.

Is there a reason we need to maintain both functions?

**Comment by Bernhard10** [comment]
There is also `get_multiloop_nucleotides` which seems to be unused.

**Comment by pkerpedjiev** [comment]
From what I can tell, `get_shortest_bg_loop` operates on nucleotides whereas `find_bulge_loop` operates on cg elements. `find_multiloop_loops` seems to find all multiloop loops.

**Comment by Bernhard10** [comment]
Forgi 2.0 now has
-  `find_bulge_loop` for the shortest loop involving the element (can contain interior loops), on the level of elements.
- `find_mlonly_multiloops` for the shortest loop containing only `m`, `t` and `f` segments, for all loops.

And some convenience functions which are thin wrappers around `find_mlonly_multiloops`:
- `shortest_mlonly_multiloop` for the shortest loop involving one element, containing only `m`, `t` and `f` segments
- `junctions` - property, to list all regular multiloops
