### ISSUE TITLE
Main README at forgi site: https://github.com/ViennaRNA/forgi - is forgi part of ViennaRNA?

### ISSUE THREAD

**Issue by shevegen** [ViennaRNA/forgi#22]
Hallo Bernhard und co,

Tut leid für nicht-englisch hier aber die meisten verstehen wohl eh die deutsche Sprache.

Ist https://github.com/ViennaRNA/forgi Teil von ViennaRNA? Eventuell könnte man das bei https://github.com/ViennaRNA/forgi ins README einfügen, wenn forgi Teil von ViennaRNA 
ist; ich dachte zuerst das forgi eigenständig ist, dann habe ich aber anhand der URL
geschlossen, das forgi eigentlich sowieso Teil der ViennaRNA suite ist. (Dachte es wäre
eigenständig und wollte schon fragen ob es "standalone releases" von forgi gibt, aber
das macht wohl keinen Sinn  wenn es eh Teil von ViennaRNA ist).

**Comment by Bernhard10** [comment]
Forgi ist eigenständig.

Das ViennaRNA in der URL ist unsere Organisation auf github. Das heißt einfach, dass wir es nicht im privaten Namespace eines Studenten haben wollen, sondern es im Instituts-Namespace "ViennaRNA" lebt. Es ist aber nicht teil des ViennaRNA **packages**.

Es gibt releases, die auf github zu finden sind. Demnächst wird außerdem Release 1.0 kommen.
