### ISSUE TITLE
release date 1.0?

### ISSUE THREAD

**Issue by budach** [ViennaRNA/forgi#23]
Hi!
I am planning to release a python3 package that needs forgi as a dependency. I've seen that with release 1.0 forgi will support python 3 and right now I am already successfully using the release-1.0 branch of forgi in my code. The problem is that the release-1.0 branch is not a valid git repository and I have to manually turn it into one and therefore it can't be automatically installed by pip.
Is there already a rough release date?

**Comment by Bernhard10** [comment]
Hi.
I guess I can get it done by the middle of October.

**Comment by Bernhard10** [comment]
I have just released Version 1.0 and uploaded forgi to pypi
