### ISSUE TITLE
Small Issues 

### ISSUE THREAD

**Issue by irenekb** [ViennaRNA/forgi#26]
**Installation:**
The following dependency is required:
https://github.com/Bernhard10/logging_exceptions.git

**Example run:**
I have to clarify the following small issue – in the latest version the example input is restricted to the folder “input”, which results in an amendment of the examples in the ReadMe file.
Additional the 1y26.cg changed to 1y26_fixed.cg and is now missing.

**Comment by Bernhard10** [comment]
Thanks. I updated the readme and documentation on the master branch.
