### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by irenekb** [ViennaRNA/forgi#27]
As far as I know Windows doesn´t like subprocess:

>python .\examples\visualize_pdb.py .\examples\input\1y26.pdb

Errormessage: [https://pastebin.com/xKTnHJtM](url)

subprocess.Popen(..) can be probable solved with (visualize_pdb.py 168):
`p = sp.Popen([sys.executable,'pymol', f2.name, f1.name], stdout=sp.PIPE, stderr=sp.PIPE)`

**Comment by Bernhard10** [comment]
In this case this obscoure error message is probably generated because you did not install `MC-Annotate`.
