### ISSUE TITLE
Possible small typo

### ISSUE THREAD

**Issue by shevegen** [ViennaRNA/forgi#29]
Hello, not sure if it is a typo, and if it is one worth to report it, but I'll report it anyway and you can decide whether it should be corrected or not - please do feel free to close this issue request at any moment in time.

To the possible typo:

At: https://viennarna.github.io/forgi/_modules/forgi/threedee/model/descriptors.html#asphericity

The docstring includes:

"The gyration tensor is defiens as in doi:10.1063/1.4788616, eq. 4"

I believe it should be "is defined as in" instead; I assume that it links to the article
linked in via the doi number, so I assume "defiens" to be a typo rather than a 
french word. :)

**Comment by Bernhard10** [comment]
Thanks. Fixed in the development branch
