### ISSUE TITLE
Can fixed dependencies be loosened?

### ISSUE THREAD

**Issue by croth1** [ViennaRNA/forgi#32]
```
networkx==2
matplotlib==2
appdirs==1.4
```

Can these dependencies be converted to >= or is it necessary to pin specific version? Asking for resolving https://github.com/bioconda/bioconda-recipes/pull/9745#issuecomment-408894402.

**Comment by Bernhard10** [comment]
Yes, they can be converted to >=.

**Comment by croth1** [comment]
Resolved, thanks :-)
